DROP TABLE IF EXISTS company;

CREATE TABLE company(
  id VARCHAR(250) NOT NULL PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  mailAddress VARCHAR(250) DEFAULT NULL,
  address VARCHAR(250) DEFAULT NULL,
  rank INT DEFAULT NULL,
);